# target position is defining 
# the end-effector position of the manipulator
# X, Y, Z are the position in meter
# r, p, y are the orientation in degrees 
target_position:
  ros__parameters:
    X: 0.5
    Y: 0.4
    Z: 0.8
    r: 90.0
    p: 180.0
    y: 180.0

collision_objects:
  ros__parameters:
    object_names: ["block","spere","cylinder","cone"]
    shape_types: [1,2,3,4]
    shape_dimensions_0: [0.5, 0.25, 1.0, 1.0]
    shape_dimensions_1: [0.5, 0.0, 0.25, 0.25]
    shape_dimensions_2: [0.5, 0.0, 0.0, 0.0]
    X: [0.0, 1.0, 2.0, 3.0]
    Y: [0.0, 0.0, 0.0, 0.0]
    Z: [2.0, 2.0, 2.0, 2.0]
    r: [0.0, 0.0, 0.0, 0.0]
    p: [0.0, 0.0, 0.0, 0.0]
    y: [0.0, 0.0, 0.0, 0.0]


# base_movement defines the motion profile
# be aware deceleration has to be defined with a minus symbol(-)
# position is defined in meters, velocity in m/s, acceleration m/s2
base_movement:   
  ros__parameters:
    max_pos: [0.6,0.8,1.5]
    max_v: [0.25,0.05,0.25]
    max_a: [0.1,-0.25,0.25,-0.1]
