# target position is defining 
# the end-effector position of the manipulator
# X, Y, Z are the position in mm
# r, p, y are the orientation in degrees 
target_position:
  ros__parameters:
    X: 0.0
    Y: 200.0
    Z: 250.0
    r: 0.0
    p: 0.0
    y: 0.0

# collision_objects:
#   ros__parameters:
#     shape_type: [1,2]
#     shape_dimensions: [[1,1,1],3]
#     X: [500.0, 500.0]
#     Y: [-500.0, 500.0]
#     Z: [50.0, 50.0]
#     r: [30.0, 0]
#     p: [10.0, 0]
#     y: [5.0, 0]

# base_movement:
#   ros__parameters:
#     pos: [500.0]
#     max_v: [0.25]
#     max_a: [0.5]
#     max_d: [0.5]
